#!/usr/bin/env python3

import logging

LOG = logging
LOGGING_LEVEL_LOGFILE = LOG.INFO
LOGGING_LEVEL_CONSOLE = LOG.INFO
LOGGING_FILENAME = '/var/log/rpcs.log'

MYSQL_DATABASE = 'db'
MYSQL_USER = 'dbadmin'
MYSQL_PASSWORD = 'h662sQ#k'

RPCSD_INTERFACE = '0.0.0.0'
RPCSD_PORT = 9116
RPCSD_TIMEOUT = 20
